### ISSUE TITLE
AttributeError: module 'InvertedIndex1' has no attribute 'main'

### ISSUE THREAD

**Issue by WK-GiHu** [MTXIII/InvIndex-w-tkinter#1]
@MTXIII 

>AttributeError: module 'InvertedIndex1' has no attribute 'main'

First you have make the `'InvertedIndex.py'`  to a Python module, add at Line 149

https://github.com/MTXIII/InvIndex-w-tkinter/blob/fdf547c3226e4763a57d9fc9dd2ede3a15619e6f/InvertedIndex.py#L149

    if __name__ == "__main__":
        main()

**Comment by MTXIII** [comment]
ah, okay I see.
So by doing this will I be able to import the main function? 
Or am I misunderstanding things?

**Comment by WK-GiHu** [comment]
@MTXIII 

>So by doing this will I be able to import the main function?

Yes, this allows the file `'InvertedIndex.py'` to be imported as a module without running the function `main()`. If you run the file using: `python InvertedIndex.py` the `if __name__ ...` becomes `True` and you can run the `main()` for testing.

**Comment by WK-GiHu** [comment]
If got this, you can close this Issue.
As it stands, you can't use `main()` within the GUI.
See https://github.com/MTXIII/InvIndex-w-tkinter/issues/3, my suggestion to add `def index_lookup_query(search_term): `

**Comment by MTXIII** [comment]
Thank you very much @WK-GiHu
