### ISSUE TITLE
Import InvIndex as bck

### ISSUE THREAD

**Issue by WK-GiHu** [MTXIII/InvIndex-w-tkinter#2]
https://github.com/MTXIII/InvIndex-w-tkinter/blob/b0a119415670b8ef16116a111d91bf66e25318b0/tkinterGUI.py#L2

Should read:

    import InvertedIndex as bck

**Comment by MTXIII** [comment]
ah yes, that's what i have been doing. I added the coment to show you what I would be importing it as but forgot to remove to .py my appologies.
