### ISSUE TITLE
InvertedIndex.main is not usabel with `tkinter`

### ISSUE THREAD

**Issue by WK-GiHu** [MTXIII/InvIndex-w-tkinter#3]
@MTXIII 

Your function `def main()` has a `input(...` therefore this function is not usabel with `tkinter`

Did you need the `index.`?
- [ ] Yes
- [ ] No

**Comment by MTXIII** [comment]
ah, ok. 

Yes, when i run the InvIndex on the command line i get:
Enter term to search for: moon
1 1
5 1
6 1

Would this not be 'result' within the main function?

**Comment by WK-GiHu** [comment]
> Would this not be 'result' within the main function?

Yes, but you can't acces a function local variabel.

Change the following:

Add at Line 101 the following:
https://github.com/MTXIII/InvIndex-w-tkinter/blob/a8893f4ba42fcdd3c92f83aa09120666b5d5ef13/InvertedIndex.py#L101

    def index_lookup_query(search_term):  

Move the Line 102
https://github.com/MTXIII/InvIndex-w-tkinter/blob/a8893f4ba42fcdd3c92f83aa09120666b5d5ef13/InvertedIndex.py#L102

to Line 137
https://github.com/MTXIII/InvIndex-w-tkinter/blob/a8893f4ba42fcdd3c92f83aa09120666b5d5ef13/InvertedIndex.py#L137

**Comment by MTXIII** [comment]
ok, I have updated the changes. So since 'result' is a local variable i cannot access it from other files. What if i made it a global variable?

**Comment by WK-GiHu** [comment]
>What if i made it a global variable?

Avoid using `global`, use it only as a last resort.
Here it will not help, you have to overcome the `input(....`

**Comment by MTXIII** [comment]
ok, understood. 

I've updated the file with your changes.
When you say verify by running 'main()', you mean run the InvertedIndex.py file?
Sorry if this is a foolish question, as mentioned I'm new to python.

**Comment by WK-GiHu** [comment]
>When you say verify by running 'main()', you mean run the InvertedIndex.py file?

Yes, see https://github.com/MTXIII/InvIndex-w-tkinter/issues/1

**Comment by MTXIII** [comment]
After updating the changes and running the file it runs and asks for the term to search for, but after entering the term it throws:
  File "InvertedIndex2.py", line 151, in <module>
    main()
  File "InvertedIndex2.py", line 147, in main
    document = db.get(appearance.docId)
NameError: name 'db' is not defined

**Comment by MTXIII** [comment]
ah, 'db' is defined in the 'index_lookup_query' function now, not 'main()'.

**Comment by WK-GiHu** [comment]
@MTXIII 
> NameError: name 'db' is not defined

Please update the file `InvertedIndex.py`

**Comment by MTXIII** [comment]
Updated.

**Comment by WK-GiHu** [comment]
@MTXIII 

Change to, note the first 2 Lines in the function goes to `def main()`
```
# def index_lookup_query(search_term):  
def index_documents(index):
    document1 = {
    ...

def main():
    db = Database()
    index = InvertedIndex(db)  
    index_documents(index)

    search_term = input('Enter term to search for: ')
    result = index.lookup_query(search_term)    
    ...
```

**Comment by MTXIII** [comment]
I've made those changes, but by commenting out `# def index_lookup_query(search_term): ` at line 96 the program throws a `NameError: 'search_term is not defined` 
(I deleted the commented out highlighting code above so the line numbers shifted)

`search_term` was an attribute of `index_lookup_query` but we've replaced that with `index_documents(index)` and we try to return it at the end of the function.

**Comment by WK-GiHu** [comment]
The Line 137
https://github.com/MTXIII/InvIndex-w-tkinter/blob/f6170e5b4a17b750fe3edd2ddf3f1bfb0f7b7764/InvertedIndex2.py#L137

have to be revertet to his previous state, note the `.` instead `_`
```
   result = index.lookup_query(search_term)
```

**Comment by MTXIII** [comment]
ah, my mistake.

**Comment by MTXIII** [comment]
Got it, I should have realized it was no longer needed. 

Ok, so the program is functioning properly now. Since we've made it into a Python module via `if __name__ ...` I should now be able to import InvertedIndex2.py to the tkinter file and call `searching = bck.main.result.get() ` (line 10 of tkinterGUI.py) to fill the results into the second window.
Am I understanding this correctly?

**Comment by WK-GiHu** [comment]
>I should now be able to import InvertedIndex2.py to the tkinter file 

Yes

>and call searching = bck.main.result.get() 

No, wait a minute i write new Issue.
