### ISSUE TITLE
In the InverseIndex.py file: I now have duplicate lines

### ISSUE THREAD

**Issue by WK-GiHu** [MTXIII/InvIndex-w-tkinter#6]
Also a separate question, In the InverseIndex3.py file:
I now have duplicate lines of:

>     db = Database()
>     index = InvertedIndex(db) 
>     index_documents(index)
>     result = index.lookup_query(search_term)

(line 97 & line 140) 
Since we've created the index_lookup_query and included those lines inside, can I get rid of them in the main function or are they still needed?

_Originally posted by @MTXIII in https://github.com/MTXIII/InvIndex-w-tkinter/issues/4#issuecomment-566819322_

**Comment by WK-GiHu** [comment]
@MTXIII 

You have decided to implement `def index_lookup_query(search_term):`

- [ ] 1. Move the whole function definition down, before `def main()`
- [ ] 2. Change `main()`, to:
 ```
def main():
    search_term = input('Enter term to search for: ')
    # Hold the next line, for now it's unclear which data type we need here
    # result = index_lookup_query(search_term)    

    for line in index_lookup_query(search_term)	
        print(line)
    print("-----------------------------")    

    # Unknow, why this is needed?
    # The output is not used?
    # document = db.get(appearance.docId)

 ```
- [ ] Run it and verify the output

**Comment by MTXIII** [comment]
Success!
